package pe.upeu.navigationjpc.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

//material foundation
val blue_primaryLight = Color(0xFF415F91)
val blue_onPrimaryLight = Color(0xFFFFFFFF)
val blue_primaryContainerLight = Color(0xFFD6E3FF)
val blue_onPrimaryContainerLight = Color(0xFF284777)
val blue_secondaryLight = Color(0xFF565F71)
val blue_onSecondaryLight = Color(0xFFFFFFFF)
val blue_secondaryContainerLight = Color(0xFFDAE2F9)
val blue_onSecondaryContainerLight = Color(0xFF3E4759)
val blue_tertiaryLight = Color(0xFF705575)
val blue_onTertiaryLight = Color(0xFFFFFFFF)
val blue_tertiaryContainerLight = Color(0xFFFAD8FD)
val blue_onTertiaryContainerLight = Color(0xFF573E5C)
val blue_errorLight = Color(0xFFBA1A1A)
val blue_onErrorLight = Color(0xFFFFFFFF)
val blue_errorContainerLight = Color(0xFFFFDAD6)
val blue_onErrorContainerLight = Color(0xFF93000A)
val blue_backgroundLight = Color(0xFFF9F9FF)
val blue_onBackgroundLight = Color(0xFF191C20)
val blue_surfaceLight = Color(0xFFF9F9FF)
val blue_onSurfaceLight = Color(0xFF191C20)
val blue_surfaceVariantLight = Color(0xFFE0E2EC)
val blue_onSurfaceVariantLight = Color(0xFF44474E)
val blue_outlineLight = Color(0xFF74777F)
val blue_outlineVariantLight = Color(0xFFC4C6D0)
val blue_scrimLight = Color(0xFF000000)
val blue_inverseSurfaceLight = Color(0xFF2E3036)
val blue_inverseOnSurfaceLight = Color(0xFFF0F0F7)
val blue_inversePrimaryLight = Color(0xFFAAC7FF)
val blue_surfaceDimLight = Color(0xFFD9D9E0)
val blue_surfaceBrightLight = Color(0xFFF9F9FF)
val blue_surfaceContainerLowestLight = Color(0xFFFFFFFF)
val blue_surfaceContainerLowLight = Color(0xFFF3F3FA)
val blue_surfaceContainerLight = Color(0xFFEDEDF4)
val blue_surfaceContainerHighLight = Color(0xFFE7E8EE)
val blue_surfaceContainerHighestLight = Color(0xFFE2E2E9)

val blue_primaryDark = Color(0xFFAAC7FF)
val blue_onPrimaryDark = Color(0xFF0A305F)
val blue_primaryContainerDark = Color(0xFF284777)
val blue_onPrimaryContainerDark = Color(0xFFD6E3FF)
val blue_secondaryDark = Color(0xFFBEC6DC)
val blue_onSecondaryDark = Color(0xFF283141)
val blue_secondaryContainerDark = Color(0xFF3E4759)
val blue_onSecondaryContainerDark = Color(0xFFDAE2F9)
val blue_tertiaryDark = Color(0xFFDDBCE0)
val blue_onTertiaryDark = Color(0xFF3F2844)
val blue_tertiaryContainerDark = Color(0xFF573E5C)
val blue_onTertiaryContainerDark = Color(0xFFFAD8FD)
val blue_errorDark = Color(0xFFFFB4AB)
val blue_onErrorDark = Color(0xFF690005)
val blue_errorContainerDark = Color(0xFF93000A)
val blue_onErrorContainerDark = Color(0xFFFFDAD6)
val blue_backgroundDark = Color(0xFF111318)
val blue_onBackgroundDark = Color(0xFFE2E2E9)
val blue_surfaceDark = Color(0xFF111318)
val blue_onSurfaceDark = Color(0xFFE2E2E9)
val blue_surfaceVariantDark = Color(0xFF44474E)
val blue_onSurfaceVariantDark = Color(0xFFC4C6D0)
val blue_outlineDark = Color(0xFF8E9099)
val blue_outlineVariantDark = Color(0xFF44474E)
val blue_scrimDark = Color(0xFF000000)
val blue_inverseSurfaceDark = Color(0xFFE2E2E9)
val blue_inverseOnSurfaceDark = Color(0xFF2E3036)
val blue_inversePrimaryDark = Color(0xFF415F91)
val blue_surfaceDimDark = Color(0xFF111318)
val blue_surfaceBrightDark = Color(0xFF37393E)
val blue_surfaceContainerLowestDark = Color(0xFF0C0E13)
val blue_surfaceContainerLowDark = Color(0xFF191C20)
val blue_surfaceContainerDark = Color(0xFF1D2024)
val blue_surfaceContainerHighDark = Color(0xFF282A2F)
val blue_surfaceContainerHighestDark = Color(0xFF33353A)

val textColor=Color(0xFFFFFFFF)
val Purple200=Color(0xFFFFFFFF)